USE VLSDB;

CREATE TABLE LOGIN(LOGIN_ID INT NOT NULL PRIMARY KEY , PASSWORD VARCHAR(30) NOT NULL);

INSERT INTO LOGIN VALUES 
(101, 'PASS101');

CREATE TABLE COURSE(COURSE_ID INT PRIMARY KEY, COURSE_NAME VARCHAR(30), 
AUTHOR_NAME VARCHAR(30), DURATION TIME, AVAILABILITY TINYINT);

INSERT INTO COURSE VALUES
(1, 'MYSQL', 'SOFIA V', '02:30:00', 1);

SELECT * FROM LOGIN;
